/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author WALTER
 */
public class Menu_IU extends javax.swing.JFrame {

    public String dni_global;

    /**
     * Creates new form Menu_IU
     */
    public Menu_IU() {
        initComponents();

    }

    public Menu_IU(String dni) {
        initComponents();
        dni_global = dni;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnProductos = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnVentas = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_mantenimiento = new javax.swing.JMenu();
        menu_item_categoria = new javax.swing.JMenuItem();
        menu_item_marca = new javax.swing.JMenuItem();
        menu_item_producto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_item_correlativo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menu_item_cliente = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menu_item_usuario = new javax.swing.JMenuItem();
        menu_ventas = new javax.swing.JMenu();
        menu_item_realizar_ventas = new javax.swing.JMenuItem();
        menu_item_anular_venta = new javax.swing.JMenuItem();
        menu_salir = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menu_reportes = new javax.swing.JMenu();
        menu_item_reporte_ventas = new javax.swing.JMenuItem();
        menu_item_reporte_productos = new javax.swing.JMenuItem();
        menu_item_reporte_venta_estado = new javax.swing.JMenuItem();
        menu_item_reporte_venta_documento = new javax.swing.JMenuItem();
        menu_item_reporte_venta_tipo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setExtendedState(6);
        setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jToolBar1.setRollover(true);

        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/caja.png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setFocusable(false);
        btnProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnProductos);
        jToolBar1.add(jSeparator4);

        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/carrito.png"))); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setFocusable(false);
        btnVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnVentas);
        jToolBar1.add(jSeparator5);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/mujer_hombre.png"))); // NOI18N
        jButton1.setText("Deudas");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 877, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        menu_mantenimiento.setText("MANTENIMIENTO");
        menu_mantenimiento.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        menu_item_categoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu_item_categoria.setText("Categoria");
        menu_item_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_categoriaActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_item_categoria);

        menu_item_marca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu_item_marca.setText("Marca");
        menu_item_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_marcaActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_item_marca);

        menu_item_producto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu_item_producto.setText("Producto");
        menu_item_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_productoActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_item_producto);
        menu_mantenimiento.add(jSeparator1);

        menu_item_correlativo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu_item_correlativo.setText("Correlativo");
        menu_item_correlativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_correlativoActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_item_correlativo);
        menu_mantenimiento.add(jSeparator2);

        menu_item_cliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu_item_cliente.setText("Cliente");
        menu_item_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_clienteActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_item_cliente);
        menu_mantenimiento.add(jSeparator3);

        menu_item_usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu_item_usuario.setText("Usuario");
        menu_item_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_usuarioActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_item_usuario);

        jMenuBar1.add(menu_mantenimiento);

        menu_ventas.setText("VENTAS");
        menu_ventas.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        menu_item_realizar_ventas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu_item_realizar_ventas.setText("Realizar Venta");
        menu_item_realizar_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_realizar_ventasActionPerformed(evt);
            }
        });
        menu_ventas.add(menu_item_realizar_ventas);

        menu_item_anular_venta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu_item_anular_venta.setText("Anular Venta");
        menu_item_anular_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_anular_ventaActionPerformed(evt);
            }
        });
        menu_ventas.add(menu_item_anular_venta);

        jMenuBar1.add(menu_ventas);

        menu_salir.setText("DEUDA");
        menu_salir.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        menu_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_salirActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Crear Cuenta Nueva");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_salir.add(jMenuItem1);

        jMenuItem2.setText("Cancelar Cuenta");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu_salir.add(jMenuItem2);

        jMenuItem3.setText("Revisar Deudores");
        menu_salir.add(jMenuItem3);

        jMenuBar1.add(menu_salir);

        menu_reportes.setText("REPORTES");
        menu_reportes.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        menu_item_reporte_ventas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu_item_reporte_ventas.setText("Reporte de Ventas por fechas");
        menu_item_reporte_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_reporte_ventasActionPerformed(evt);
            }
        });
        menu_reportes.add(menu_item_reporte_ventas);

        menu_item_reporte_productos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu_item_reporte_productos.setText("Reporte de Productos");
        menu_item_reporte_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_reporte_productosActionPerformed(evt);
            }
        });
        menu_reportes.add(menu_item_reporte_productos);

        menu_item_reporte_venta_estado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu_item_reporte_venta_estado.setText("Reporte de Ventas por estado");
        menu_item_reporte_venta_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_reporte_venta_estadoActionPerformed(evt);
            }
        });
        menu_reportes.add(menu_item_reporte_venta_estado);

        menu_item_reporte_venta_documento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu_item_reporte_venta_documento.setText("Reporte de Ventas por documentos");
        menu_item_reporte_venta_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_reporte_venta_documentoActionPerformed(evt);
            }
        });
        menu_reportes.add(menu_item_reporte_venta_documento);

        menu_item_reporte_venta_tipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu_item_reporte_venta_tipo.setText("Reporte de Ventas por tipo de venta");
        menu_item_reporte_venta_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_reporte_venta_tipoActionPerformed(evt);
            }
        });
        menu_reportes.add(menu_item_reporte_venta_tipo);

        jMenuBar1.add(menu_reportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_item_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_usuarioActionPerformed
        // TODO add your handling code here:
        Usuario_IU frame = new Usuario_IU();
        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();
    }//GEN-LAST:event_menu_item_usuarioActionPerformed

    private void menu_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_salirActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menu_salirActionPerformed

    private void menu_item_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_marcaActionPerformed
        // TODO add your handling code here:
        Marca_IU frame = new Marca_IU();
        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();
    }//GEN-LAST:event_menu_item_marcaActionPerformed

    private void menu_item_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_categoriaActionPerformed

        Categoria_IU frame = new Categoria_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();

    }//GEN-LAST:event_menu_item_categoriaActionPerformed

    private void menu_item_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_clienteActionPerformed

        Cliente_IU frame = new Cliente_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();

    }//GEN-LAST:event_menu_item_clienteActionPerformed

    private void menu_item_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_productoActionPerformed

        Producto_IU frame = new Producto_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();

    }//GEN-LAST:event_menu_item_productoActionPerformed

    private void menu_item_correlativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_correlativoActionPerformed

        Correlativo_IU frame = new Correlativo_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();


    }//GEN-LAST:event_menu_item_correlativoActionPerformed

    private void menu_item_realizar_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_realizar_ventasActionPerformed

        Venta_IU frame = new Venta_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();

    }//GEN-LAST:event_menu_item_realizar_ventasActionPerformed

    private void menu_item_anular_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_anular_ventaActionPerformed

        AnularVenta_IU frame = new AnularVenta_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();

    }//GEN-LAST:event_menu_item_anular_ventaActionPerformed

    private void menu_item_reporte_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_reporte_productosActionPerformed

        ReporteProductos_IU frame = new ReporteProductos_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();

    }//GEN-LAST:event_menu_item_reporte_productosActionPerformed

    private void menu_item_reporte_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_reporte_ventasActionPerformed

        ReporteVentasDMA_IU frame = new ReporteVentasDMA_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();

    }//GEN-LAST:event_menu_item_reporte_ventasActionPerformed

    private void menu_item_reporte_venta_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_reporte_venta_estadoActionPerformed

        ReporteVentasEstado_IU frame = new ReporteVentasEstado_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();

    }//GEN-LAST:event_menu_item_reporte_venta_estadoActionPerformed

    private void menu_item_reporte_venta_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_reporte_venta_documentoActionPerformed
        
        ReporteVentasDocumentos_IU frame = new ReporteVentasDocumentos_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();
        
    }//GEN-LAST:event_menu_item_reporte_venta_documentoActionPerformed

    private void menu_item_reporte_venta_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_reporte_venta_tipoActionPerformed
        
        ReporteVentasTipo_IU frame = new ReporteVentasTipo_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();
        
    }//GEN-LAST:event_menu_item_reporte_venta_tipoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        AperturaCuenta_IU frame = new AperturaCuenta_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         Deuda_IU frame = new Deuda_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_IU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnProductos;
    public javax.swing.JButton btnVentas;
    public static javax.swing.JDesktopPane escritorio;
    public javax.swing.JButton jButton1;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JMenuItem jMenuItem3;
    public javax.swing.JPopupMenu.Separator jSeparator1;
    public javax.swing.JPopupMenu.Separator jSeparator2;
    public javax.swing.JPopupMenu.Separator jSeparator3;
    public javax.swing.JToolBar.Separator jSeparator4;
    public javax.swing.JToolBar.Separator jSeparator5;
    public javax.swing.JToolBar jToolBar1;
    public javax.swing.JMenuItem menu_item_anular_venta;
    public javax.swing.JMenuItem menu_item_categoria;
    public javax.swing.JMenuItem menu_item_cliente;
    public javax.swing.JMenuItem menu_item_correlativo;
    public javax.swing.JMenuItem menu_item_marca;
    public javax.swing.JMenuItem menu_item_producto;
    public javax.swing.JMenuItem menu_item_realizar_ventas;
    public javax.swing.JMenuItem menu_item_reporte_productos;
    public javax.swing.JMenuItem menu_item_reporte_venta_documento;
    public javax.swing.JMenuItem menu_item_reporte_venta_estado;
    public javax.swing.JMenuItem menu_item_reporte_venta_tipo;
    public javax.swing.JMenuItem menu_item_reporte_ventas;
    public javax.swing.JMenuItem menu_item_usuario;
    public javax.swing.JMenu menu_mantenimiento;
    public javax.swing.JMenu menu_reportes;
    public javax.swing.JMenu menu_salir;
    public javax.swing.JMenu menu_ventas;
    // End of variables declaration//GEN-END:variables
}
