/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import CapaNegocio.DetalleVentaBD;
import CapaNegocio.VentaBD;
import static CapaPresentacion.AnularVenta_IU.tabla_pedidos;
import static CapaPresentacion.Venta_IU.tabla_pedidos;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WALTER
 */
public class ReporteVentasDMA_IU extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReporteVentasDMA_IU
     */
    public ReporteVentasDMA_IU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dcFechaInicio = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        dcFechaFinal = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_reporte_detalle_venta = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_reporte_venta = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        txtCantidadProductos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCantidadVentas = new javax.swing.JTextField();

        setClosable(true);
        setTitle("REPORTE DE VENTAS X DIA - MES - AÑO");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("FECHA INICIO");

        dcFechaInicio.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        dcFechaInicio.setMaxSelectableDate(new java.util.Date(253370786468000L));
        dcFechaInicio.setMinSelectableDate(new java.util.Date(-62135747932000L));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("FECHA FINAL");

        dcFechaFinal.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        dcFechaFinal.setMaxSelectableDate(new java.util.Date(253370786468000L));
        dcFechaFinal.setMinSelectableDate(new java.util.Date(-62135747932000L));

        tabla_reporte_detalle_venta.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tabla_reporte_detalle_venta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_reporte_detalle_venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabla_reporte_detalle_ventaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_reporte_detalle_venta);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("DETALLE DE LA VENTAS...");

        tabla_reporte_venta.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tabla_reporte_venta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_reporte_venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabla_reporte_ventaMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tabla_reporte_venta);

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtCantidadProductos.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtCantidadProductos.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("CANTIDAD DE PRODUCTOS");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("CANTIDAD DE VENTAS");

        txtCantidadVentas.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtCantidadVentas.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCantidadProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dcFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 437, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCantidadVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(dcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidadVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addComponent(btnBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(392, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        DefaultTableModel tabla_temporal_venta;

        int dia = dcFechaInicio.getCalendar().get(Calendar.DAY_OF_MONTH);
        int anio = dcFechaInicio.getCalendar().get(Calendar.YEAR);
        int mes = dcFechaInicio.getCalendar().get(Calendar.MONTH) + 1;
        String fechaInicio = anio + "-" + mes + "-" + dia;

        dia = dcFechaFinal.getCalendar().get(Calendar.DAY_OF_MONTH);
        anio = dcFechaFinal.getCalendar().get(Calendar.YEAR);
        mes = dcFechaFinal.getCalendar().get(Calendar.MONTH) + 1;
        String fechaFinal = anio + "-" + mes + "-" + dia;

        VentaBD objeto_ventaBD = new VentaBD();
        tabla_temporal_venta = objeto_ventaBD.reportarVentaFecha(fechaInicio, fechaFinal);
        tabla_reporte_venta.setModel(tabla_temporal_venta);

        int cantLista = tabla_temporal_venta.getRowCount();
        txtCantidadVentas.setText("" + cantLista);


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tabla_reporte_detalle_ventaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_reporte_detalle_ventaMousePressed


    }//GEN-LAST:event_tabla_reporte_detalle_ventaMousePressed

    private void tabla_reporte_ventaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_reporte_ventaMousePressed

        int fila_seleccionada = tabla_reporte_venta.getSelectedRow();
        
        DefaultTableModel tabla_temporal_venta = (DefaultTableModel) tabla_reporte_venta.getModel();
        
        int idventa=Integer.parseInt(tabla_temporal_venta.getValueAt(fila_seleccionada, 0).toString());
        
        DetalleVentaBD objeto_detalleVentaBD=new DetalleVentaBD();
        tabla_temporal_venta=objeto_detalleVentaBD.buscarDetalleVenta(idventa);
        
        tabla_reporte_detalle_venta.setModel(tabla_temporal_venta);
               
        int cantLista = tabla_temporal_venta.getRowCount();
        txtCantidadProductos.setText("" + cantLista);

    }//GEN-LAST:event_tabla_reporte_ventaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private com.toedter.calendar.JDateChooser dcFechaFinal;
    private com.toedter.calendar.JDateChooser dcFechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla_reporte_detalle_venta;
    private javax.swing.JTable tabla_reporte_venta;
    private javax.swing.JTextField txtCantidadProductos;
    private javax.swing.JTextField txtCantidadVentas;
    // End of variables declaration//GEN-END:variables
}
