/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import CapaNegocio.VentaBD;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WALTER
 */
public class ReporteVentasDocumentos_IU extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReporteVentasDocumentos_IU
     */
    public ReporteVentasDocumentos_IU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCantidadVentas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_reporte_venta = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        cmbDocumento = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("REPORTE DE VENTAS POR DOCUMENTOS");

        txtCantidadVentas.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtCantidadVentas.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("DOCUMENTO");

        tabla_reporte_venta.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tabla_reporte_venta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_reporte_venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabla_reporte_ventaMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tabla_reporte_venta);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("CANTIDAD DE VENTAS");

        cmbDocumento.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cmbDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOLETA", "TICKET" }));
        cmbDocumento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDocumentoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 1009, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCantidadVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabla_reporte_ventaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_reporte_ventaMousePressed

    }//GEN-LAST:event_tabla_reporte_ventaMousePressed

    private void cmbDocumentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDocumentoItemStateChanged
        
        DefaultTableModel tabla_temporal;
        String estado=cmbDocumento.getSelectedItem().toString();
        
        VentaBD objeto_ventaBD=new VentaBD();
        tabla_temporal=objeto_ventaBD.buscarVentaDocumento(estado);
        
        tabla_reporte_venta.setModel(tabla_temporal);
        
        int cantidadLista = tabla_temporal.getRowCount();
        txtCantidadVentas.setText("" + cantidadLista);
        
        
    }//GEN-LAST:event_cmbDocumentoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla_reporte_venta;
    private javax.swing.JTextField txtCantidadVentas;
    // End of variables declaration//GEN-END:variables
}
